services:
  - type: web
    name: pokezentrum-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: CHAT_ID
        fromSecret: CHAT_ID
    build:
      environment:
        pythonVersion: 3.10.13
